export const OBTER_PROJETOS = 'OBTER_PROJETOS'
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO'
export const ALTERAR_PROJETO_ASYNC = 'ALTERAR_PROJETO_ASYNC'
export const REMOVER_PROJETO_ASYNC = 'REMOVER_PROJETO_ASYNC'

export const OBTER_TAREFAS = 'OBTER_TAREFAS'
export const CADASTRAR_TAREFAS = 'CADASTRAR_TAREFAS'
export const ALTERAR_TAREFA_ASYNC = 'ALTERAR_TAREFA_ASYNC'

